version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./server:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./server:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./docker/mysql/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cake_tutorial
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
